# Reading ALWIND_07_12 dataset
wind = read.csv("E:\\New folder\\ALWIND_07_12.csv")
wind
head(wind)

# Summary for our Dataset
summary(wind)

# Checking whether is their any null values
sum(is.na(wind))

# Checking is their any outliers with Boxplot
boxplot(wind$Air_temperature,wind$Pressure,wind$Wind.speed,wind$Wind.direction,wind$Power.generated.by.system)

# Histograms for checking Distribution Frequency
hist(wind$Air_temperature, xlab = "Air Temperature")
hist(wind$Pressure, xlab = "Pressure")
hist(wind$Wind.speed, xlab = "Wind Speed")
hist(wind$Wind.direction, xlab = "WInd Direction")
hist(wind$Power.generated.by.system, xlab = "Power Generated by System")

# LinePlots for our DataSet
plot(wind$Air_temperature, xlab = "Air Temperature", type = "l")
plot(wind$Pressure, xlab = "Pressure", type = "l")
plot(wind$Wind.speed, xlab = "Wind Speed", type = "l")
plot(wind$Wind.direction, xlab = "Wind Direction", type = "l")
plot(wind$Power.generated.by.system, xlab = "Power Generated by System", type = "l")

help(lm)

wind_lr = lm(wind$Power.generated.by.system ~ wind$Air_temperature + wind$Pressure + wind$Wind.speed + wind$Wind.direction)
summary(wind_lr)

cor(wind$Air_temperature, wind$Pressure)
cor(wind$Wind.speed, wind$Wind.direction)

plot(wind_lr)
