# Reading ALWIND_07_12 dataset
wind = read.csv("E:\\New folder\\ALWIND_07_12.csv")
wind
head(wind)

# Summary for our Dataset
summary(wind)

# Checking whether is their any null values
sum(is.na(wind))

# Checking is their any outliers with Boxplot and Removing them
boxplot(wind$Air_temperature, xlab = "Air Temperature")
o1 = boxplot(wind$Air_temperature)$out
which(wind$Air_temperature %in%  o1)
wind = wind[-which(wind$Air_temperature %in% o1),]
boxplot(wind$Air_temperature, xlab = "Air Temperature")

boxplot(wind$Pressure, xlab = "Wind Pressure")
o2 = boxplot(wind$Pressure)$out
which(wind$Pressure %in% o2)
wind = wind[-which(wind$Pressure %in% o2), ]
boxplot(wind$Pressure, xlab = "Wind Pressure")

boxplot(wind$Wind.speed, xlab = "Wind Speed")
o3 = boxplot(wind$Wind.speed)$out
which(wind$Wind.speed %in% o3)
wind = wind[-which(wind$Wind.speed %in% o3),]
boxplot(wind$Wind.speed, xlab = "Wind Speed")

boxplot(wind$Wind.direction, xlab = "Wind Driection")

boxplot(wind$Power.generated.by.system, xlab = "Power Generated by System")
o4 = boxplot(wind$Power.generated.by.system)$out
which(wind$Power.generated.by.system %in% o4)
wind = wind[-which(wind$Power.generated.by.system %in% o4),]
boxplot(wind$Power.generated.by.system, xlab = "Power Generated by system")

# Histograms for checking Distribution Frequency
hist(wind$Air_temperature, xlab = "Air Temperature")
hist(wind$Pressure, xlab = "Pressure")
hist(wind$Wind.speed, xlab = "Wind Speed")
hist(wind$Wind.direction, xlab = "WInd Direction")
hist(wind$Power.generated.by.system, xlab = "Power Generated by System")

# LinePlots for our DataSet
plot(wind$Air_temperature, xlab = "Air Temperature", type = "l")
plot(wind$Pressure, xlab = "Pressure", type = "l")
plot(wind$Wind.speed, xlab = "Wind Speed", type = "l")
plot(wind$Wind.direction, xlab = "Wind Direction", type = "l")
plot(wind$Power.generated.by.system, xlab = "Power Generated by System", type = "l")

# Correlation
cor(wind$Air_temperature, wind$Pressure)
cor(wind$Wind.speed, wind$Wind.direction)

help(lm)

# Model Evaluation 
wind_lr = lm(wind$Power.generated.by.system ~ wind$Air_temperature + wind$Pressure + wind$Wind.speed + wind$Wind.direction)
summary(wind_lr)

plot(wind_lr)
